Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
  events:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for events'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-events
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: "S"
        - AttributeName: timestamp
          AttributeType: "S"
        - AttributeName: processing_time
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: processing_time
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
            - AttributeName: processing_time
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  eventsName:
    Description: "The name of this DynamoDB table."
    Value: !Ref events
    Export: 
      Name: !Sub ${App}-${Env}-eventsTableName
  eventsDynamoDBTableARN:
    Description: "The ARN of the events DynamoDB table."
    Value: !GetAtt events.Arn
    Export: 
      Name: !Sub ${App}-${Env}-eventsTableArn
